// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CounterButton: typeof import('./components/CounterButton.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
  }
}

export { }
